services:

  pg:
    image: postgres
    environment:
      POSTGRES_DB: exchange_service
      POSTGRES_USER: exchange_service
      POSTGRES_PASSWORD: exchange_service
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    ports:
      - "8080:8080"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.org
      PGADMIN_DEFAULT_PASSWORD: exchange_service
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"