"""create currencu table

Revision ID: b99138989fdf
Revises: 
Create Date: 2024-09-09 02:18:42.747814

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b99138989fdf"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "currency",
        sa.Column(
            "id",
            sa.Uuid(),
            server_default=sa.text("gen_random_uuid()"),
            nullable=False,
        ),
        sa.Column("num_code", sa.Integer(), nullable=False),
        sa.Column("char_code", sa.String(), nullable=False),
        sa.Column("nominal", sa.Integer(), nullable=False),
        sa.Column("name_rate", sa.String(), nullable=False),
        sa.Column("value_rate", sa.Float(), nullable=False),
        sa.Column("vunit_rate", sa.Float(), nullable=False),
        sa.Column("date", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_currency")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("currency")
    # ### end Alembic commands ###
